---
community_name: OpenHarmony-TPC-Security
community_logo_url: 
community_org_url: https://gitee.com/openharmony-tpc
resource_types:
    software-artifact-repositories:
        repo_urls: 
        - https://github.com/weidai11/cryptopp
        - https://github.com/leizongmin/js-xss
        - https://github.com/apache/shiro
        - https://github.com/str4d/ed25519-java
    governance-repositories:
        repo_urls: []

    