---
community_name: openGauss_Security
community_logo_url: https://gitee.com/opengauss.png
community_org_url: https://gitee.com/opengauss
resource_types:
    software-artifact-repositories:
        repo_urls: 
        - https://gitee.com/opengauss/security
    governance-repositories:
        repo_urls: []
    